### ISSUE TITLE
[Snekeval] TODO

### ISSUE THREAD

**Issue by wereii** [wereii/we-cogs#4]
- [ ] Docstrings
- [ ] Review typing anotations
- [ ] Add links to [snekbox](https://github.com/python-discord/snekbox)
- [ ] Document the cog  (README.md)
- [ ] Cleanup `info.json`
